//Data Type Definition Generated by RPC compiler. Please do not modify this file.
namespace app
{
	/// <summary>
	/// the RPC service example.
	/// </summary>
	public class AppService
	{
		public AppService(string baseUrl){
			BaseUrl = baseUrl;
		}
		public string BaseUrl { get; set; }
		/// <summary>
		/// this is genarate a list of image slides for the front end to display
		/// </summary>
		public async System.Threading.Tasks.Task<ImageItem[]> ImageList()
		{
			return NodeJSRPC.Converter.convertJsonResponse<ImageItem[]>(await NodeJSRPC.HttpClient.Post(this.BaseUrl + "/app/app.rpc.js?AppService-ImageList", ));
		}
		/// <summary>
		/// File upload
		/// </summary>
		/// <param name="file"></param>
		public async System.Threading.Tasks.Task<string> upload(NodeJSRPC.Polyfill.File file)
		{
			return NodeJSRPC.Converter.convertStringResponse(await NodeJSRPC.HttpClient.Post(this.BaseUrl + "/app/app.rpc.js?AppService-upload", file));
		}
		/// <summary>
		/// transfer of bytes
		/// </summary>
		/// <param name="file"></param>
		public async System.Threading.Tasks.Task<bool> transfer(NodeJSRPC.Polyfill.Blob file)
		{
			return NodeJSRPC.Converter.convertBooleanResponse(await NodeJSRPC.HttpClient.Post(this.BaseUrl + "/app/app.rpc.js?AppService-transfer", file));
		}
	}
}
